# Generated by Django 6.0.3 on 2026-03-17 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_optional_fields'),
        ('patients', '0002_optional_phone'),
        ('services', '0002_hospitalservice_alter_service_hospitals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reference', models.DateTimeField(auto_now_add=True)),
                ('motif_consultation', models.TextField()),
                ('trouvailles_cliniques', models.TextField()),
                ('diagnostic', models.TextField()),
                ('examens_faits', models.TextField(blank=True)),
                ('traitements_recus', models.TextField(blank=True)),
                ('raisons_reference', models.TextField()),
                ('niveau_urgence', models.CharField(choices=[('TRES_URGENT', 'Très Urgent'), ('MOYENNE', 'Moyenne urgence'), ('FAIBLE', 'Faible urgence')], default='FAIBLE', max_length=20)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('trouvailles_reception', models.TextField(blank=True, null=True)),
                ('soins_administres', models.TextField(blank=True, null=True)),
                ('evolution_favorable', models.BooleanField(default=None, null=True)),
                ('besoin_suivi', models.BooleanField(default=False)),
                ('date_rendez_vous', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('commentaires_destinataire', models.TextField(blank=True, null=True)),
                ('hopital_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrantes', to='hospitals.hospital')),
                ('hopital_referent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortantes', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'references_reference',
            },
        ),
        migrations.CreateModel(
            name='ReferenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.reference')),
            ],
        ),
    ]
