# Generated by Django 6.0.3 on 2026-05-21 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_optional_fields'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='hopital_referent',
        ),
        migrations.AddField(
            model_name='reference',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='hospital_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='references_envoyees', to='hospitals.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='hospital_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_recues', to='hospitals.hospital'),
        ),
    ]
