# Generated by Django 6.0.3 on 2026-03-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        ('references', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='hospital_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_references', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='reference',
            name='hospital_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_references', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='reference',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='reference',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
        migrations.AddField(
            model_name='referencehistory',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.reference'),
        ),
    ]
