# Generated by Django 6.0.3 on 2026-03-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_optional_fields'),
        ('references', '0003_referencehistory_changed_by'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='hospital_destination',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='hospital_source',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='status',
        ),
        migrations.AddField(
            model_name='reference',
            name='besoin_suivi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='commentaires_destinataire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='date_rendez_vous',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='diagnostic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='evolution_favorable',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='examens_faits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='hopital_destinataire',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='entrantes', to='hospitals.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='hopital_referent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sortantes', to='hospitals.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='motif_consultation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='niveau_urgence',
            field=models.CharField(choices=[('TRES_URGENT', 'Très Urgent'), ('MOYENNE', 'Moyenne urgence'), ('FAIBLE', 'Faible urgence')], default='FAIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='reference',
            name='raisons_reference',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='soins_administres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='traitements_reçus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='trouvailles_cliniques',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='trouvailles_reception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='reference',
            table='references_table',
        ),
    ]
