# Generated by Django 6.0.3 on 2026-03-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_optional_fields'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'hospital_services',
                'managed': True,
                'unique_together': {('hospital', 'service')},
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='hospitals',
            field=models.ManyToManyField(related_name='services_list', through='services.HospitalService', to='hospitals.hospital'),
        ),
    ]
